<?php
    session_start();
    if(!isset($_SESSION['email'])) {
        header("Location: login.php");
    }
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MyCar</title>
    <link rel="stylesheet" href="assets/css/terms_service.css"/>
</head>
<body>
    <nav class="navbar">
        <div class="logo">
            <img id="logo-image" src="assets/css/pic/mycarlogo1.png" alt="MyCar Logo">
        </div>
        <div class="button">
            <a class="btn-primary">Go Back</a>
        </div>
    </nav>
    <div class="container">
        <center>
            <h1><b>Terms And Conditions</b></h1>
        </center>
        <br>
        <div class="et_pb_text_inner"><p style="text-align: justify;">Last update: 01 September 2023</p>
            <p style="text-align: justify;">This page sets out the terms and conditions (“Terms of Use”) for using the MyCar e-hailing application (“Application”). The Application is owned and operated by Platform Apps Sdn Bhd (and/or its subsidiaries for the purpose of enabling users seeking transportation services (“Passenger”) to certain destinations to be matched with third party independent transportation providers (“Driver, you, your”) for a certain fare (“Service”).</p>
            <p style="text-align: justify;"><strong><u>PLEASE READ THESE TERMS OF USE CAREFULLY BEFORE USING THIS APPLICATION. YOU SHOULD IMMEDIATELY STOP AND REFRAIN FROM USING THIS APPLICATION IF YOU DO NOT AGREE TO THIS TERMS OF USE.</u></strong></p>
            <p style="text-align: justify;"><strong><u>MyCar’s Passenger Terms and Conditions.</u></strong></p>
            <p style="text-align: justify;">The booking of a ride made through MyCar app (“Book a Ride, Booking a Ride”) and the performance of the ride to the selected destination by the Driver (hereinafter defined) (“Service”) shall be governed by the terms and conditions herein after appearing and shall be the legally binding document between you and Platform Apps Sdn Bhd 1254600-X (“MyCar, us, our, we”).</p>
            <p style="text-align: justify;">By Booking a ride and using the Service, you are deemed to have read, understood and expressly agreed to be bound by this Terms and Conditions, which may be amended, modified, added, deleted and corrected at any time and at the sole discretion of MyCar. Therefore, you are advised to review this Terms and Conditions periodically to be aware of such changes. Further, you agree and accept that the updated Terms and Conditions shall supersede all previous versions of the Terms and Conditions with automatic and immediate effect once they are posted on our App and/or the MyCar App and/or website, without any further action by us and that you shall be bound by the terms of the most recent version of the Terms and Conditions found on the MyCar App and/or the MyCar website.</p>
            <p style="text-align: justify;">In addition to this Term and Conditions, you shall also be bound by the Terms of Use and Privacy Statement of MyCar, which may be amended and revised from time to time.</p>
            <p style="text-align: justify;">You acknowledge that the MyCar App is only a platform for you to Book a Ride (“App”) with an available driver. Further, you agree that the Service is performed and fulfilled by the driver who is an independent third party and not an employee of MyCar (“Driver”).</p>
            <p style="text-align: justify;">Platform Apps Sdn Bhd (“MyCar”) is the merchant of records for every Book a Ride. &nbsp;Therefore the receipt for your Book a ride shall appear in the name of MyCar and any refunds shall also be processed and made by MyCar.</p>
            <p style="text-align: justify;"><strong>A. Book a Ride</strong></p>
            <ol style="text-align: justify;">
            <li>To Book a Ride: You must have the legal capacity to be bound by this Terms and Conditions and that you are at least eighteen (18) years old. As and when requested, you shall provide us with your personal identification document for security and identity verification purposes; and you will need to be MyCar Passenger and log on to the MyCar Application account. You can register to be MyCar Passenger here.</li>
            <li>You are responsible to provide all information required in the App for the purpose of provision and fulfilment of the Service and to update your personal information in the App from time to time to ensure it is accurate and current.</li>
            <li>You shall provide the actual number of passengers when you Book a Ride as and when you are requested to do so. In the event that that the number of passengers is untrue or inaccurate, you hereby agree that the Driver is entitled to cancel your booking and may charge a Cancellation Fee as per the Cancellation Policy as set out below.</li>
            <li>You will have the option to consent and allow access for the App to the use of the Global Positioning System (GPS). MyCar recommend that you provide your consent in order for &nbsp;the App &nbsp;to &nbsp;be able to indicate the locations accurately.</li>
            <li>You shall select the correct pick-up and/or drop-off locations before you confirm to Book a Ride.</li>
            <li>Changes in pick-up and/or drop-off locations are not allowed. You are to ensure that your pick-up and/or drop-off locations are accurate prior to Booking a Ride. &nbsp;If you wish to change your pick-up and/or drop-off locations, you are required to cancel the existing Book a Ride, and book a new ride with the accurate location.</li>
            <li>You are advised to confirm to Book a Ride only when you are ready to travel. The Driver has the right to terminate your booking if the Driver has been waiting for longer than Five (5) minutes.</li>
            <li>You are entitled to cancel the Book a Ride if you notice that the vehicle or the Driver’s details do not match the details shown in the MyCar App.</li>
            </ol>
            <p style="text-align: justify;"><strong>B. Payment</strong></p>
            <ol style="text-align: justify;">
            <li>You are required to make payment for the charges incurred for the provision of the Service including any applicable tolls, taxes and any other fees or charges due.</li>
            <li>You may select the method of payment at the time of Book a Ride, which may be in the form of cash, Card, MyCar Reward Points (coming soon), e-Wallet or one of the automated payment methods made available on the App from time to time. Any method of payment so selected is non-changeable and irrevocable.</li>
            <li>Despite selecting cash or e-Wallet as the method of Payment, you are advised to register at least one valid automated payment method in the App prior to Book a Ride. Automated payment methods shall be in the form of credit card or debit card (“Card”).</li>
            <li>You shall register a valid Card that belongs to you in accordance with the step-by-step instructions as provided in the App. In the event the Card belongs to another person, you hereby warrant and represent that you have obtained the permission from such person to use the Card for the payment of the Service. You agree that MyCar may verify and authenticate the Card details when you first register the Card in the App as well as when you Book a Ride.</li>
            <li>If the tipping feature is available in the App, you may pre-set a default “tip” amount when you Book a Ride. This will automatically be included in the total payment due after the Service has been provided, and the tipping amount will be paid to the Driver.</li>
            <li>MyCar may, in its sole discretion, create promotional codes that may be redeemed for the booking of the Services, subject to any additional terms that MyCar establishes on a per promotional code basis.</li>
            <li>Passengers should not remit any additional payment to the Driver apart from the total payable amount reflected in the App. MyCar App’s records will be the evidence of payment and we shall not be responsible for any dispute of payment exceeding the total amount payable reflected in the App.</li>
            </ol>
            <p style="text-align: justify;"><strong>C. Cancellation Policy</strong></p>
            <ol style="text-align: justify;">
            <li>You may cancel your book a ride at any time before a Driver is assigned to you. If you decide to cancel your book a ride or do not show up at the designated location where the Driver is supposed to pick you up, you agree that you may be charged a fee (“Cancellation Fee”) which will be reflected in your next book a ride as stipulated in this cancellation policy.</li>
            <li>Subject to the above Clause 1 of C, if you use debit/credit to pay for the fare/charges and subsequently you or the Driver cancel the ride, the money will automatically be reversed back to your designated bank account.</li>
            <li>Once a Driver is assigned and arrives at the pickup location, the Service may be considered as completed. Cancelling at this point might result in charges and/or no refund.</li>
            <li>You may contact MyCar chat support available in the App or contact us at <a href="mailto:support@mycarasia.com">support@mycarasia.com</a> for any Q&amp;A.</li>
            </ol>
            <p style="text-align: justify;"><strong>D. Refund</strong></p>
            <ol style="text-align: justify;">
            <li>If you wish to apply for a refund, you may do so in accordance with the MyCar refund policy.</li>
            </ol>
            <p style="text-align: justify;"><strong>[Refund for all mode of payments].</strong></p>
            <ol start="2" style="text-align: justify;">
            <li>Submission of refund shall be made to MyCar’s chat support and our team will be in touch with you for an investigation for approval.</li>
            <li>Upon approval of refund, we will refund you through “online” where you will be able to perform the withdrawal of funds to your designated bank account.</li>
            <li>Upon request of withdrawal of funds, please allow fourteen (14) working days for us to process the withdrawal process.</li>
            <li>Once a Driver is assigned and arrives at the pickup location, the Service may be considered as completed. Cancelling at this point might result in charges and/or <strong>no refund</strong>.</li>
            </ol>
            <p style="text-align: justify;"><strong>E. Rights and Obligations</strong></p>
            <ol style="text-align: justify;">
            <li>This Service can be procured by you for yourself or for the use by other persons with or without your company. Should you procure the Service for another person without your company, you shall ensure such person must have attained the minimum age of 12 years old to be an unaccompanied passenger (“Unaccompanied Minor”). Further, you agree that you shall assume the primary responsibility of the conduct and/or behaviour of such person during the use of the Service including the Unaccompanied Minor;</li>
            <li>You shall behave appropriately and in good manners and shall not discriminate against or harass anyone on the basis of race, national origin, religion, gender, gender identity or expression, physical or mental disability, medical condition, marital status, age or sexual orientation;</li>
            <li>You shall not request your Driver to speed or commit traffic violations, including dropping off and/or picking up at illegal or unsafe locations;</li>
            <li>You shall always wear seat belts at all times during the Service provision and shall ensure such other persons traveling with or without you to do the same. If you are travelling with children or babies, you shall be responsible to ensure that the appropriate safety measures as per the applicable laws are adhered throughout the provision of the Service.</li>
            <li>You must abide by the Standard Operating Procedures (“SOP”) set by the relevant regulatory authorities, including but not limited to, the number of passenger(s) allowed in the vehicle and wearing face masks. The Driver has the option to reject your Book a Ride should you not follow the relevant SOP.</li>
            <li>You shall be penalised by law for any attempts to vandalise, damage, theft or robbery to the Driver’s vehicle.</li>
            <li>In the event that you suspect your Driver to be under the influence of illegal substances, you have the right to terminate the Service and report to the local authorities and/or us.</li>
            <li>In the event of an emergency, you shall contact the authorities first. Once all parties are safe and the authorities have been contacted, you may report the incident to us. For avoidance of doubt, there is an “SOS” feature available in the App which allows you to contact the authorities in the event of an emergency.</li>
            <li>You reserve the right to cancel your Book a Ride at any time before the commencement of Service. However, such cancellation may be subject to a Cancellation Fee as stipulated above.</li>
            <li>You shall be responsible for your own personal belongings. MyCar will not compensate for any losses suffered for loss of personal belongings.</li>
            <li>You are not allowed to contact your Driver after the Service has completed. Except in the event that you necessarily believe that you have lost an item, you may contact your Driver and arrange for a collection.</li>
            <li>Upon completion of the Service, you shall have the option to rate your Driver and to provide feedback.</li>
            </ol>
            <p style="text-align: justify;"><strong>F. Miscellaneous</strong></p>
            <p style="text-align: justify;"><strong></strong></p>
            <ol>
            <li style="text-align: justify;">You will only use the Application to carry out the Service for their intended and lawful purposes;</li>
            <li style="text-align: justify;">You will keep your account password or any identification we provide you which allows access to the Application secure and confidential;</li>
            <li style="text-align: justify;">You agree to notify us immediately of any unauthorized use of your account or any other breach of security;</li>
            <li style="text-align: justify;">You will not try to interrupt or harm the Application in any way;</li>
            <li style="text-align: justify;">You will not attempt to commercially exploit any part of the Application without our permission, including without limitation modify any of the Application’s content in any way, or copy, reproduce, publicly display, distribute or otherwise use or communicate them for any public or commercial purpose without our permission;</li>
            <li style="text-align: justify;">You will not authorize others to use your identity or user status, and you may not assign or otherwise transfer your user account to any other person or entity;</li>
            <li style="text-align: justify;">You will provide us with whatever proof of identity or any other documents, permits, licenses or approvals which we may reasonably request or require;</li>
            <li style="text-align: justify;">You will not use the Application for sending or storing any unlawful material or for fraudulent purposes;</li>
            <li style="text-align: justify;">You will not copy, or distribute the content of the Application Software or other content without written permission from MyCar;</li>
            <li style="text-align: justify;">You will provide accurate, current and complete information as required for the Service and undertake the responsibility to maintain and update your information in a timely manner to keep it accurate, current and complete at all times during the term of the Agreement. You agree that we may rely on your information as accurate, current and complete. You acknowledge that if your information is untrue, inaccurate, not current or incomplete in any respect, we have the right but not the obligation to terminate this Agreement at any time with or without notice;</li>
            <li style="text-align: justify;">You will only use an access point or data account which you are authorized to use;</li>
            <li style="text-align: justify;">You agree that your use of the Application will be subject to our Privacy Policy;</li>
            <li style="text-align: justify;">You will not utilise modified devices or applications with the intent of evading detections or facilitating any activities intended to defraud MyCar or to disrupt the natural functions of the Application;</li>
            <li style="text-align: justify;">You shall not reverse look-up, trace or seek to trace any information on any Passenger, or any other customer of MyCar, including without limitation any user account not owned by you, to its source, or exploit the Application or any service or information made available or offered by or through the Application, in any way where the purpose is to reveal any information, including but shall not be limited to personal identification information, other than your own information, as provided for by the Application;</li>
            <li style="text-align: justify;">In the course of your performance of the Service, you acknowledge that MyCar may disclose Personal Data of other individuals to you and you undertake that you will only use such Personal Data for any other purposes not associated with the performance of the Service;</li>
            <li style="text-align: justify;">You shall not license, sublicense, sell, transfer, assign, distribute or otherwise commercially exploit or make available to any third party the Application in any way; modify or make derivative works based on the Application; “mirror” the Application on any other server or wireless or internet-based device; except to the extent such restriction is prohibited under applicable law, disassemble, decompile, reverse engineer, decrypt or attempt to derive and code or extract software from, this Application or any software or services made available on or through the Application; use any manual or automated program or script, including but not limited to web spiders, web crawlers, web robots, web ants, web indexers, bots, viruses or worms, or any program which may make multiple server requests per second, (a) to unduly burden or hinder the operation and/or performance of the Application; (b) to conduct data mining or scraping activities, or (b) in any way reproduce or circumvent the navigational structure or presentation of the Application or its content; post, distribute or reproduce in any way any copyrighted material, trademarks, or other proprietary information without obtaining the prior consent of the owner of such proprietary right; remove any copyright, trademark or other proprietary rights notices contained on the Application; or use the Application to: (a) send spam or otherwise duplicative or unsolicited messages; (b) send or store infringing, obscene, threatening, libelous, or otherwise unlawful or tortious material, including but not limited to materials harmful to children or violative of third party privacy rights; (c) send material containing software viruses, worms, trojan horses or other harmful computer code, files, scripts, agents or programs; (d) interfere with or disrupt the integrity or performance of the Application or the data contained therein; (e) attempt to gain unauthorized access to the Application or its related software, systems or networks; (f) impersonate any person or entity or otherwise misrepresent your affiliation with a person or entity; or (g) engage in any conduct that could possibly damage our reputation or amount to being disreputable.</li>
            <li style="text-align: justify;">You agree and acknowledge and accept that a failure to comply with the Term of Use may result in suspension of this grant of right. This Application is governed by the laws of Malaysia and should there be any dispute arising from your use of this Application, you further agree to submit to the exclusive jurisdiction of the Malaysia courts.</li>
            <li style="text-align: justify;">These Terms and Conditions will prevail over any inconsistent terms, conditions, provisions or representations contained in any other promotional materials regarding MyCar. In the event of any inconsistency between the terms in this Terms and Conditions and other provisions or materials, this Terms and Conditions shall prevail.</li>
            <li style="text-align: justify;">We shall not be liable for any failure to comply with or for any delay in performing our obligations where the failure is caused by something outside our reasonable control. Such circumstances shall include, but not limited to, weather conditions, fire, flood, hurricane, strike, industrial dispute, war, hostilities, political unrest, riots, civil commotion, epidemic and pandemic as pronounced by the World Health Organisation, inevitable accidents, supervening legislation or any other circumstances of whatsoever nature beyond the control of ours.</li>
            <li style="text-align: justify;">We reserve the right at our sole discretion to vary, delete or add to any of the Terms and Conditions contained herein and/or cancel, terminate or suspend your book a ride from time to time without any prior notice, and such revised terms and conditions will be posted on the App immediately. For the avoidance of doubt, cancellation, termination or suspension by us of your access to the App or book a ride shall not entitle you to any claim or compensation against us for any and all losses or damage howsoever arising, whether or not we or you have been advised of the possibility of such loss or damage.</li>
            <li style="text-align: justify;">You agree to defend and indemnify us and any of our officers, directors, employees and agents from and against any claims, causes of action, demands, recoveries, losses, damages, fines, penalties or other costs or expenses of any kind or nature including but not limited to reasonable legal fees, brought by third parties, including the Driver, as a result of your breach of this Terms and Conditions and your violation of any rights or applicable laws.</li>
            <li style="text-align: justify;">We shall bear no responsibility for any damage, loss (including but not limited to direct, indirect and consequential loss), liability, injury or disappointment incurred or suffered by you) in connection with the Service, the promotion of this Service, except for any liability which cannot be excluded by law (in which case that liability is limited to the minimum allowable by law).</li>
            <li style="text-align: justify;">These Terms and Conditions shall be governed by and interpreted in accordance with the laws of Malaysia.</li>
            </ol></div>                
    </hr>
            <div class="et_pb_text_inner"><p style="text-align: justify;"><strong>MyCar’s&nbsp; Drivers Terms and Conditions.</strong></p>
                <p style="text-align: justify;"><strong>PLEASE READ THESE TERMS OF USE CAREFULLY BEFORE USING THIS APPLICATION. YOU SHOULD IMMEDIATELY STOP AND REFRAIN FROM USING THIS APPLICATION IF YOU DO NOT AGREE TO THIS TERMS OF USE.</strong></p>
                <p style="text-align: justify;">This MyCar Driver’s Service Agreement shall govern the relationship between Platform Apps Sdn Bhd (“MyCar, us, we”) and the Driver, which is to be read together and shall collectively represent a legally binding agreement (“Agreement”) between the Parties.</p>
                <p style="text-align: justify;">Platform Apps Sdn Bhd is the owner and operator of the MyCar App e-hailing application (“Application”) that is available on the mobile application (“Platform”) for the purpose of enabling users seeking transportation services (“Passenger”) to certain destinations to be matched with third party independent transportation providers (“Driver, you, your”) for a certain fare (“Service”).</p>
                <p style="text-align: justify;">By clicking the Accept &amp; Agree button in the Driver’s Registration Form, you agree that you have read, understood, accepted and agreed with these terms and conditions.</p>
                <p><strong></strong><strong>A. Term</strong></p>
                <p style="text-align: justify;">This Agreement shall commence on the date where your registration as a Driver is confirmed by MyCar (“Effective Date”) and shall continue indefinitely unless terminated pursuant to Clause I below in this Agreement.</p>
                <p><strong>B. Grant of Rights</strong></p>
                <p style="text-align: justify;">From the Effective Date and in exchange for the Remuneration (hereunder defined), we hereby grant you a revocable, non-exclusive, non- transferable, limited license to use and access the Application to enable you to perform the Service subject to the terms and conditions of this Agreement. You shall also abide by and adhere to the Term of Use of the Application at all times, which may be changed and/or amended from time to time. You are advised to keep yourself updated with the latest version of the Term of Use.</p>
                <p><strong>C. Drivers’ Obligations</strong></p>
                <p style="text-align: justify;">During the Term of this Agreement, you undertake that;</p>
                <ol style="text-align: justify;">
                <li>You possess a valid driver’s license and a public vehicle service license (“PSV License”) and have obtained an e-hailing vehicle permit (“EVP”) in order to operate a motor vehicle;</li>
                <li>The vehicle which you intend to use when performing the Service (“Vehicle”), is in good operating condition and meets the industry safety standards for Vehicles of its kind;</li>
                <li>You will strictly adhere and comply with road safety standards, as imposed by the applicable laws;</li>
                <li>You shall possess the necessary insurance policy required under the applicable laws for third party and public liability coverage for the Vehicle and to cover any anticipated losses incurred as a result of performing the Service;</li>
                <li>You shall carry out the performance of the Service in compliance with and in the manner as stipulated under Schedule A – Code of Conduct;</li>
                <li>You agree to assist us with any internal or external investigations as may be required by us in complying with any prevailing laws or regulations in place;</li>
                <li>You shall not, at any time after accepting a Book a Ride, unreasonably cancel the performance of Service to such booking; and</li>
                <li>any other obligation that we may impose from time to time at our discretion.</li>
                </ol>
                <p><strong>D. Payments</strong></p>
                <ol style="text-align: justify;">
                <li>Payment Terms for Drivers</li>
                </ol>
                <p style="text-align: justify;">1.1 The fees which you pay us for the completion of each Service are due immediately and are non-refundable (“Commission“). The Commission shall be a percentage of the fee charged to passengers, as determined by us from time to time. The percentage of Commission shall be based on the category of drivers and vehicles and will be displayed to you in the Application.</p>
                <p style="text-align: justify;">1.2 This no-refund policy shall apply at all times regardless of your decision to terminate this Agreement, our decision to terminate or suspend your access to the Application, disruption caused to the Service whether planned, accidental or intentional, or any reason whatsoever.</p>
                <p style="text-align: justify;">1.3 You acknowledge and confirm that we may collect on your behalf the total due to you for certain payment methods chosen by the Passenger. We retain the right to suspend the processing of any transaction where we reasonably believe that the transaction may be fraudulent, illegal or involves any criminal activity or where you and/or the Passenger have breached any of the terms in this Agreement. In such an event, you shall not hold us liable for any withholding of, delay in, suspension, forfeiture or cancellation of, any payment(s) to you.</p>
                <p style="text-align: justify;">1.4 &nbsp; We may, at our sole discretion, make promotional offers with different features and different rates on the Service to any of the Passenger whereby these promotional offers shall accordingly be honoured by you. We may change the Commission rate at any time at our sole discretion.</p>
                <ol start="2" style="text-align: justify;">
                <li>Driver’s Cash Wallet</li>
                </ol>
                <p style="text-align: justify;">2.1 MyCar shall administer payments to you and from you by way of a wallet system (the “Driver’s Cash Wallet”). Your earnings will be displayed in the Driver’s Cash Wallet in the Application and may be withdrawn by you to your designated bank account. MyCar reserves the right to make such deductions from the Driver’s Cash Wallet as are provided for in these terms and conditions, as are authorized by you, or as are notified to you via the Application. The amount to be withdraw at least RM 20.00 and above. Upon on withdrawal process, it takes 7 to 14 working days.</p>
                <ol start="3" style="text-align: justify;">
                <li>Driver’s Credit Wallet</li>
                </ol>
                <p style="text-align: justify;">3.1 In addition to your Driver’s Cash Wallet, you must also maintain with us a Driver’s Credit Wallet. The Driver’s Credit Wallet store credits comprises a pre-payment to us by you of the Commission and other fees and charges applicable due and payable by you to us. You must at all times maintain a minimum credit balance (“Minimum Balance”) in your Driver’s Credit Balance in order for you to use the Service. The amount of such Minimum Balance shall be prescribed by us, and shall be notified to you through the Application. It may be changed at any time at our sole discretion.</p>
                <p style="text-align: justify;">3.2 You may add funds (“Credits”) to your Driver’s Credit Wallet to fulfil the Minimum Balance requirement. The maximum balance you may hold in the Driver’s Cash Wallet at any time is RM300.00. Balance may be added in any manner prescribed by us from time to time (such as cash</p>
                <p style="text-align: justify;">3.3 <strong>Credits Wallet are</strong> <strong>not redeemable</strong> for cash and cannot be refunded. They cannot be resold, exchanged or transferred for value under any circumstances. The <strong>Credits Wallet</strong> shall not be regarded, construed, or used as valuable or exchangeable instruments under any circumstances. You will not receive interest or other earnings on your Credits. We may receive interest on amounts that we hold on your behalf. You agree to assign your rights to us for any interest derived from your Credits.</p>
                <p style="text-align: justify;">3.4 Credits in the Driver’s Credit Wallet will expire one (1) year from the date of your last top up. If there should be any balance upon the expiration of Credit, the balance will not be refunded. To avoid any forfeiture of credit, we advise you to perform a top up once before the expiration of credit for the total credit to be extended for another one (1) year. Minimum top up is RM20.00 and above.</p>
                <p><strong>E. Taxes</strong></p>
                <p style="text-align: justify;">You are accountable for payment of any tax and statutory contributions due in respect of the sums payable to you under or in connection with this Agreement. You also acknowledge and agree that the Commission is inclusive of all and any applicable sales and service tax, goods and service tax, value added tax, withholding tax and/or other similar taxes, that are applicable and imposed pursuant to the local laws of Malaysia.</p>
                <p><strong>F. Cancellation</strong></p>
                <p style="text-align: justify;">&nbsp;The Passengers rely on you for the provision of the Service. You agree that high and/or frequent cancellation rates or ignoring the Passengers’ bookings will impair the Passengers’ experience and negatively impact the reputation and branding of MyCar. Should you be found to have violated this subclause, we shall reserve the right to take any appropriate measure against you including but not limited to restricting your Service.</p>
                <p style="text-align: justify;">1.0 Refund for Driver’s Credit Wallet</p>
                <p style="text-align: justify;">1.1 Submission of refund shall be made to the MyCar’s chat support and our team will be in touch with you for an investigation for approval.</p>
                <p style="text-align: justify;">1.2 Upon approval of refund, we will refund any fee wrongly charged to your Driver’s <strong>Credit Wallet.</strong></p>
                <p style="text-align: justify;">1.3 The refund will be processed within fourteen (14) working days.</p>
                <p><strong>H. Incentive for Driver</strong></p>
                <p style="text-align: justify;">At the sole discretion of ours, MyCar may select you as part of MyCar Driver’s incentive program. The incentive program will be communicated to you through the Applications and any applicable terms and conditions shall be communicated and made available to you through the in-app messaging function of the Application.</p>
                <p style="text-align: justify;">
                </p><p><strong>I. Suspension and Termination</strong></p>
                <p style="text-align: justify;">1.1 You agree and acknowledge and accept that a failure to comply with the Term of Use may result in suspension of this grant of right.</p>
                <p style="text-align: justify;">1.2 You agree that we may do any of the following, at any time, without notice:</p>
                <p style="text-align: justify;">(i) &nbsp;to modify, suspend or terminate operation of or access to the Application, or any portion of the Application (including access to your Account and/or the availability of any products or services), for any reason;</p>
                <p style="text-align: justify;">(ii) to modify or change any applicable policies or terms; and</p>
                <p style="text-align: justify;">(iii) to interrupt the operation of the Application or any portion of the Application (including access to your Account and/or the availability of any products or services), as necessary to perform routine or non-routine maintenance, error correction, or other changes.</p>
                <p style="text-align: justify;">We shall not be required to compensate you for any suspension or termination.</p>
                <p style="text-align: justify;">1.3 We reserve the right to immediately terminate this Agreement in the event you are in breach of Clause J [Intellectual Property Rights], Clause K [Confidentiality] and Clause M [Drivers’ Representations, Warranties and Undertakings].</p>
                <p style="text-align: justify;">1.4 We may terminate this Agreement In the event, you are in breach of your obligations as provided under this Agreement, Code of Conduct and/or Terms of Use and has failed to remedy such breach, if capable of remedy, within seven (7) days (unless otherwise stated in this Agreement), or any other extended period as agreed upon between the Parties after receipt of notice from us requesting to remedy such breach; and by written notice with a notice period of 30 days without the need to assign any reason thereof.</p>
                <p><strong>J. Intellectual Property Rights</strong></p>
                <p style="text-align: justify;">MyCar and its licensors, where applicable, shall own all right, title and interest, including all related intellectual property rights, in and to the Application and by extension, the Service and any suggestions, ideas, enhancement requests, feedback, recommendations or other information provided by you or any other party relating to the Service. The terms and conditions do not constitute a sale agreement and do not convey to you any rights of ownership in or related to the Service and/or the Application, or any intellectual property rights owned by MyCar and/or its licensors. MyCar’s name, MyCar’s logo, the Service and/or the Application and the third-party transportation providers’ logos and the product names associated with the Application are trademarks of MyCar or third parties, and no right or license is granted to use them. For the avoidance of doubt, the term Application herein shall include its respective components, processes and design in its entirety.</p>
                <p><strong>K. Confidentiality</strong></p>
                <p style="text-align: justify;">You shall maintain in confidence all information and data relating to MyCar, its services, products, business affairs, marketing and promotion plans or other operations and its associated companies which are disclosed to you by or on behalf of MyCar (whether orally or in writing and whether before, on or after the date of this Agreement) or which are otherwise directly or indirectly acquired by you from MyCar, or any of its affiliate companies, or created in the course of this Agreement. You shall further ensure that you only use such confidential information in order to use the Service, and shall not without MyCar ‘s prior written consent, disclose such information to any third party nor use it for any other purpose.</p>
                <p><strong>L. Data Privacy and Personal Data Protection Policy</strong></p>
                <p style="text-align: justify;">MyCar collects and processes your Personal Data and you agree and consent to MyCar, its subsidiaries, actual assignee, potential assignee, transferee, acquirer, in connection with any corporate restructuring plan to transfer the business, asset or it’s liability and any of its affiliate companies to be collecting, using, processing and disclosing your Personal Data in the manner deemed fit and necessary by MyCar.</p>
                <p><strong>M. Drivers’ Representations, Warranties and Undertakings</strong></p>
                <p style="text-align: justify;">During the Term of this Agreement, you represent, warrant and undertake that:</p>
                <ol style="text-align: justify;">
                <li>You have legal capacity to enter into the Agreement;</li>
                <li>You are at least eighteen (18) years old;</li>
                <li>All the information which you provide shall be true and accurate;</li>
                <li>When performing the Service, you agree to comply with all laws applicable to you and/or your performance of the Service; You own, or have the legal right and authority to operate, the Vehicle which you intend to use when performing the Service;</li>
                <li>You have all the appropriate licenses, approvals and authority to provide the Service;</li>
                <li>You shall obey all local laws related to the operation of a e-hailing service and will be solely responsible for any violations of such local laws; and You are aware that when responding to Passengers, an in-app messaging function will be made available. In the event you choose to communicate otherwise, standard telecommunication charges may apply which shall be solely borne by you.</li>
                </ol>
                <p><strong>N. Indemnification</strong></p>
                <p style="text-align: justify;">During the Term of this Agreement, you agree that you shall indemnify and hold MyCar, its licensors and each such party’s affiliates, officers, directors, members, employees, attorneys and agents harmless from and against any and all claims, costs, damages, losses, liabilities and expenses (including attorneys’ fees and costs and/or regulatory action) arising out of or in connection with: (a) your performance of the Service and any violation and breach to the Code of Conduct; or (b) your violation or breach of any of the terms and conditions of this Agreement and the Term of Use of the Application; and (c) any act or omission, negligence or wilful misconduct resulting in personal injury, death or property damage.</p>
                <p><strong>O. Disclaimer of Warranties</strong></p>
                <p style="text-align: justify;">The Application, its content and any related service(s) is provided to you on an “as is” basis. MyCar Ride makes no representations or warranties of any kind, express or implied, in connection with the Application, Platform, Service, these terms and conditions, the content or any related service(s). Although we make reasonable efforts to keep the Application up-to-date, we make no representations, warranties or guarantees, whether express or implied, that such information is accurate, complete or up to date. We shall not be liable for any direct, indirect or consequent loss arising from the modifications or amendments to the Application, Platform, Service, or terms and conditions.</p>
                <p><strong>P. Internet Delays</strong></p>
                <p style="text-align: justify;">The platform, application and/or the associated software used to maintain and operate the platform and/or application may be subject to limitations, delays, and other problems inherent in the use of the internet and electronic communications including the device used by you being faulty, not connected, out of range, switched off or not functioning. You hereby acknowledge and agree that MyCar ride is not responsible for any delays, delivery failures, damages or losses resulting from such problems.</p>
                <p><strong>Q. Limitation of Liability</strong></p>
                <p style="text-align: justify;">You shall be solely responsible for any and all claims, judgments and liabilities resulting from any accident, loss or damage including, but not limited to, personal injuries, death, total loss and property damage which is due to or is alleged to be a result of the performance of the Service by you.</p>
                <p><strong>R. Assignment</strong></p>
                <p style="text-align: justify;">This Terms and Conditions as modified from time to time shall not be assigned by you at all times. However, MyCar shall have the right to assign without your consent subject to a notice to be provided by us. Any purported assignment by you in violation of this section shall be void.</p>
                <p><strong>S. Relationship</strong></p>
                <p style="text-align: justify;">The relationship between you and MyCar shall be of the nature of independent contractors. Nothing contained in these terms and conditions shall be construed as creating any agency, partnership, or other form of joint enterprise with us.</p>
                <p><strong>T. Severability</strong></p>
                <p style="text-align: justify;">If any provision of the terms and conditions is held to be invalid or unenforceable, the legality, validity and enforceability of the remaining provisions shall not be affected or impaired.</p>
                <p><strong>U. No Waiver</strong></p>
                <p style="text-align: justify;">The failure of MyCar to enforce any right or provision in the terms and conditions shall not constitute a waiver of such right or provision.</p>
                <p><strong>V. Entire Agreement</strong></p>
                <p style="text-align: justify;">This Agreement comprises the entire agreement between you and us and supersedes any prior or contemporaneous negotiations or discussions.</p>
                <p><strong>W. Miscellaneous</strong></p>
                <ol style="text-align: justify;">
                <li>You will only use the Application to carry out the Service for their intended and lawful purposes;</li>
                <li>You will keep your account password or any identification we provide you which allows access to the Application secure and confidential;</li>
                <li>You agree to notify us immediately of any unauthorized use of your account or any other breach of security;</li>
                <li>You will not try to interrupt or harm the Application in any way;</li>
                <li>You will not attempt to commercially exploit any part of the Application without our permission, including without limitation modify any of the Application’s content in any way, or copy, reproduce, publicly display, distribute or otherwise use or communicate them for any public or commercial purpose without our permission;</li>
                <li>You will not authorize others to use your identity or user status, and you may not assign or otherwise transfer your user account to any other person or entity;</li>
                <li>You will provide us with whatever proof of identity or any other documents, permits, licenses or approvals which we may reasonably request or require;</li>
                <li>You will not use the Application for sending or storing any unlawful material or for fraudulent purposes;</li>
                <li>You will not copy, or distribute the content of the Application Software or other content without written permission from MyCar;</li>
                <li>You will provide accurate, current and complete information as required for the Service and undertake the responsibility to maintain and update your information in a timely manner to keep it accurate, current and complete at all times during the term of the Agreement. You agree that we may rely on your information as accurate, current and complete. You acknowledge that if your information is untrue, inaccurate, not current or incomplete in any respect, we have the right but not the obligation to terminate this Agreement at any time with or without notice;</li>
                <li>You will only use an access point or data account which you are authorized to use;</li>
                <li>You agree that your use of the Application will be subject to our Privacy Policy;</li>
                <li>You will not utilise modified devices or applications with the intent of evading detections or facilitating any activities intended to defraud MyCar or to disrupt the natural functions of the Application;</li>
                <li>You shall not reverse look-up, trace or seek to trace any information on any Passenger, or any other customer of MyCar, including without limitation any user account not owned by you, to its source, or exploit the Application or any service or information made available or offered by or through the Application, in any way where the purpose is to reveal any information, including but shall not be limited to personal identification information, other than your own information, as provided for by the Application;</li>
                <li>In the course of your performance of the Service, you acknowledge that MyCar may disclose Personal Data of other individuals to you and you undertake that you will only use such Personal Data for any other purposes not associated with the performance of the Service.</li>
                <li>You shall not: license, sublicense, sell, transfer, assign, distribute or otherwise commercially exploit or make available to any third party the Application in any way; modify or make derivative works based on the Application; “mirror” the Application on any other server or wireless or internet-based device; except to the extent such restriction is prohibited under applicable law, disassemble, decompile, reverse engineer, decrypt or attempt to derive and code or extract software from, this Application or any software or services made available on or through the Application; use any manual or automated program or script, including but not limited to web spiders, web crawlers, web robots, web ants, web indexers, bots, viruses or worms, or any program which may make multiple server requests per second, (a) to unduly burden or hinder the operation and/or performance of the Application; (b) to conduct data mining or scraping activities, or (c) in any way reproduce or circumvent the navigational structure or presentation of the Application or its content; post, distribute or reproduce in any way any copyrighted material, trademarks, or other proprietary information without obtaining the prior consent of the owner of such proprietary right; remove any copyright, trademark or other proprietary rights notices contained on the Application; or use the Application to: (a) send spam or otherwise duplicative or unsolicited messages; (b) send or store infringing, obscene, threatening, libelous, or otherwise unlawful or tortious material, including but not limited to materials harmful to children or violative of third party privacy rights; (c) send material containing software viruses, worms, trojan horses or other harmful computer code, files, scripts, agents or programs; (d) interfere with or disrupt the integrity or performance of the Application or the data contained therein; (e) attempt to gain unauthorized access to the Application or its related software, systems or networks; (f) impersonate any person or entity or otherwise misrepresent your affiliation with a person or entity; or (g) engage in any conduct that could possibly damage our reputation or amount to being disreputable.</li>
                <li>You agree and acknowledge and accept that a failure to comply with the Term of Use may result in suspension of this grant of right. This Application is governed by the laws of Malaysia and should there be any dispute arising from your use of this Application, you further agree to submit to the exclusive jurisdiction of the Malaysia courts.</li>
                <li>These Terms and Conditions will prevail over any inconsistent terms, conditions, provisions or representations contained in any other promotional materials regarding MyCar. In the event of any inconsistency between the terms in this Terms and Conditions and other provisions or materials, this Terms and Conditions shall prevail.</li>
                <li>We shall not be liable for any failure to comply with or for any delay in performing our obligations where the failure is caused by something outside our reasonable control. Such circumstances shall include, but not limited to, weather conditions, fire, flood, hurricane, strike, industrial dispute, war, hostilities, political unrest, riots, civil commotion, epidemic and pandemic as pronounced by the World Health Organisation, inevitable accidents, supervening legislation or any other circumstances of whatsoever nature beyond the control of ours.</li>
                <li>We reserve the right at our sole discretion to vary, delete or add to any of the Terms and Conditions contained herein and/or cancel, terminate or suspend your book a ride from time to time without any prior notice, and such revised terms and conditions will be posted on the App immediately. For the avoidance of doubt, cancellation, termination or suspension by us of your access to the App or book a ride shall not entitle you to any claim or compensation against us for any and all losses or damage howsoever arising, whether or not we or you have been advised of the possibility of such loss or damage.</li>
                <li>You agree to defend and indemnify us and any of our officers, directors, employees and agents from and against any claims, causes of action, demands, recoveries, losses, damages, fines, penalties or other costs or expenses of any kind or nature including but not limited to reasonable legal fees, brought by third parties, including the Driver, as a result of your breach of this Terms and Conditions and your violation of any rights or applicable laws.</li>
                <li>We shall bear no responsibility for any damage, loss (including but not limited to direct, indirect and consequential loss), liability, injury or disappointment incurred or suffered by you) in connection with the Service, the promotion of this Service, except for any liability which cannot be excluded by law (in which case that liability is limited to the minimum allowable by law).</li>
                <li>These Terms and Conditions shall be governed by and interpreted in accordance with the laws of Malaysia.</li>
                </ol>
                <p style="text-align: justify;">
                </p><p style="text-align: justify;"><strong>Schedule A</strong></p>
                <p style="text-align: justify;"><u>MYCAR DRIVER’S CODE OF CONDUCT</u></p>
                <ol style="text-align: justify;">
                <li>You will not use the Application to cause nuisance or behave in an inappropriate or disrespectful manner towards us, our affiliates or any third party</li>
                <li>You shall not contact Passengers for purposes other than in connection with the Service;</li>
                <li>You shall ensure that the vehicle must be maintained in good condition and regular inspection must be carried out to ensure that the said vehicle is safe, roadworthy and suitable for its intended use;</li>
                <li>You shall comply with all traffic laws and regulations imposed by the relevant authorities from time to time;</li>
                <li>You shall only use the vehicle that you have registered in the Application and should not use any other vehicle. If you are required to use another vehicle for the same account, please contact MyCar’s chat support to perform the necessary changes of information.</li>
                <li>You are prohibited to consume any alcohol, drugs and/or illegal substances prior to or during the drive;</li>
                <li>You are advisable to maintain proper decorum and dress appropriately as regulated by MyCar and/or the local authority(ies);</li>
                <li>You shall not engage in reckless driving which may pose a risk or threat to the Passenger(s) safety and wellbeing;</li>
                <li>You shall provide assistance to the Passenger(s) especially to the less able;</li>
                <li>You shall communicate with the Passenger(s) in a polite and non-abusive manner. Any vulgar words or sexual insinuation is strictly prohibited;</li>
                <li>Any form of misconduct or sexual harassment is strictly prohibited. MyCar may lodge a police report against you for any wrongdoing which can be deemed as criminal in nature;</li>
                <li>Any form of communication with the Passenger(s) which is personal and unwarranted is strictly prohibited;</li>
                <li>You shall respect if the Passenger(s) refuse to communicate and shall respect their decision and avoid making them uncomfortable;</li>
                <li>You shall always check with the Passenger(s) if they have left any item(s) or personal belonging(s) behind. Any item(s) found shall be notified and/or returned to the Passenger(s) or to MyCar;</li>
                <li>You shall not engage in job transfer and every accepted job assignment shall be honoured and completed by you;</li>
                <li>You shall not practice any form of discrimination towards different religion, race, sexuality, and towards the disabled;</li>
                <li>You are aware that overcharging Passenger(s) shall be viewed seriously. Fares are to be decided by the rates predetermined by the MyCar. You are not allowed to incur extra chargers to your Passenger(s) unless stated otherwise by MyCar via its Platform;</li>
                <li>You must ensure that face masks are to be worn at all times for both Driver and Passenger(s) in order to contain the infection of Covid-19;</li>
                <li>The number of Passenger(s) allowed in the vehicle must be subjected to the Standard Operating Procedures (SOP)/ regulations set by the relevant regulatory authorities;</li>
                <li>You shall ensure that the vehicle is sanitised from time to time and the Passenger(s) use hand sanitisers when on boarding the vehicle;</li>
                <li>MyCar shall not be responsible for any Services provided by you for any negligence, misconduct and/or wrongdoing towards the Passenger(s), other road user(s) and/or other third party(ies);</li>
                <li>You shall have the discretion to refuse Service for Passenger(s) that appear drunk or inappropriate prior to boarding the vehicle;</li>
                <li>Passengers and Drivers may be allowed to rate or block each other in respect of the Services provided.</li>
                <li>Every rating will be automatically logged onto MyCar’s system and MyCar may analyse all ratings received. MyCar may take all appropriate actions including suspending your use of the Application for performance of Service without any notice or compensation to you.</li>
                </ol>
                <p style="text-align: justify;">The Driver hereby agrees and acknowledges that MyCar has the rights to add, insert and or amend the Driver’s Code of Conduct from time to time.</p>
                <p style="text-align: justify;">
                </p><p style="text-align: justify;">
                </p><p style="text-align: justify;">
                </p><p style="text-align: justify;">
                </p><p style="text-align: justify;">
                </p><ol></ol></div>

        </div>
    </div>
</div>
<script src="assets/javascript/terms_service.js"></script>
<script src="assets/javascript/darkmode.js"></script>
</body>
</html>